<?php
$data = $block->getStatisticsData();
$breakdown = $data['breakdown'];

?>
<div class="stats-wrapper">
    <ul class="stats-list row">
        <li>
            <div class="stats-item">
                <img src="<?= $block->getViewFileUrl('Filejet_FilejetMagento2Plugin::images/master-images.svg') ?>" alt="">
                <span>
                                    <strong><?= $breakdown['masterImageAccessed'] ?></strong>
                                    Master accessed
                                    </span>
            </div>
        </li>
        <li>
            <div class="stats-item">
                                <img src="<?= $block->getViewFileUrl('Filejet_FilejetMagento2Plugin::images/renders.svg') ?>" alt="">
                <span>
                                        <strong><?= $breakdown['mutationAccessed'] ?></strong>
                                        Mutations
                                    </span>
            </div>
        </li>
        <li>
            <div class="stats-item">
                                <img src="<?= $block->getViewFileUrl('Filejet_FilejetMagento2Plugin::images/total-requests.svg') ?>" alt="">
                <span> <strong><?= $block->formatBytes($breakdown['bandwidth']) ?></strong>
                                        Bandwidth
                                    </span>
            </div>
        </li>
        <li>
            <div class="stats-item">
                                <img src="<?= $block->getViewFileUrl('Filejet_FilejetMagento2Plugin::images/avg-response.svg') ?>" alt="">
                <span>
                                        <strong><?= round($breakdown['averageResponseTime']) ?>ms</strong>
                                        Avg. response (ms)
                                    </span>
            </div>
        </li>
    </ul>
</div>
<?php

$graphData = $data['graphData'];
if ($graphData):
    $labels = array_column($graphData['masterImageAccessed'], 'day');
    $masterImageAccessed = array_column($graphData['masterImageAccessed'], 'value');
    $mutationAccessed = array_column($graphData['mutationAccessed'], 'value');
    ?>
    <div class="stats-chart" data-mage-init='{"filejet_dashboard": {"labels": "<?= implode(',', $labels) ?>", "masterImageAccessed" : "<?= implode(',', $masterImageAccessed) ?>", "mutationAccessed" : "<?= implode(',', $mutationAccessed) ?>"}}'>
        <canvas id="stats" width="400" height="200"></canvas>
        <p class="info"><i>* statistics are re-calculated every hour</i></p>
    </div>
<?php
endif;
?>

